Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sns.pairplot(df, hue="species", diag_kind="kde")
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py:3805[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3804[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3805[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3806[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32mindex.pyx:167[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mindex.pyx:196[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7081[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7089[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'species'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m [43msns[49m[38;5;241;43m.[39;49m[43mpairplot[49m[43m([49m[43mdf[49m[43m,[49m[43m [49m[43mhue[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mspecies[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdiag_kind[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mkde[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m plt[38;5;241m.[39mshow()

File [0;32m~/.local/lib/python3.12/site-packages/seaborn/axisgrid.py:2119[0m, in [0;36mpairplot[0;34m(data, hue, hue_order, palette, vars, x_vars, y_vars, kind, diag_kind, markers, height, aspect, corner, dropna, plot_kws, diag_kws, grid_kws, size)[0m
[1;32m   2117[0m [38;5;66;03m# Set up the PairGrid[39;00m
[1;32m   2118[0m grid_kws[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mdiag_sharey[39m[38;5;124m"[39m, diag_kind [38;5;241m==[39m [38;5;124m"[39m[38;5;124mhist[39m[38;5;124m"[39m)
[0;32m-> 2119[0m grid [38;5;241m=[39m [43mPairGrid[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[38;5;28;43mvars[39;49m[38;5;241;43m=[39;49m[38;5;28;43mvars[39;49m[43m,[49m[43m [49m[43mx_vars[49m[38;5;241;43m=[39;49m[43mx_vars[49m[43m,[49m[43m [49m[43my_vars[49m[38;5;241;43m=[39;49m[43my_vars[49m[43m,[49m[43m [49m[43mhue[49m[38;5;241;43m=[39;49m[43mhue[49m[43m,[49m
[1;32m   2120[0m [43m                [49m[43mhue_order[49m[38;5;241;43m=[39;49m[43mhue_order[49m[43m,[49m[43m [49m[43mpalette[49m[38;5;241;43m=[39;49m[43mpalette[49m[43m,[49m[43m [49m[43mcorner[49m[38;5;241;43m=[39;49m[43mcorner[49m[43m,[49m
[1;32m   2121[0m [43m                [49m[43mheight[49m[38;5;241;43m=[39;49m[43mheight[49m[43m,[49m[43m [49m[43maspect[49m[38;5;241;43m=[39;49m[43maspect[49m[43m,[49m[43m [49m[43mdropna[49m[38;5;241;43m=[39;49m[43mdropna[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mgrid_kws[49m[43m)[49m
[1;32m   2123[0m [38;5;66;03m# Add the markers here as PairGrid has figured out how many levels of the[39;00m
[1;32m   2124[0m [38;5;66;03m# hue variable are needed and we don't want to duplicate that process[39;00m
[1;32m   2125[0m [38;5;28;01mif[39;00m markers [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/.local/lib/python3.12/site-packages/seaborn/axisgrid.py:1327[0m, in [0;36mPairGrid.__init__[0;34m(self, data, hue, vars, x_vars, y_vars, hue_order, palette, hue_kws, corner, diag_sharey, height, aspect, layout_pad, despine, dropna)[0m
[1;32m   1316[0m     [38;5;28mself[39m[38;5;241m.[39mhue_vals [38;5;241m=[39m pd[38;5;241m.[39mSeries([[38;5;124m"[39m[38;5;124m_nolegend_[39m[38;5;124m"[39m] [38;5;241m*[39m [38;5;28mlen[39m(data),
[1;32m   1317[0m                               index[38;5;241m=[39mdata[38;5;241m.[39mindex)
[1;32m   1318[0m [38;5;28;01melse[39;00m:
[1;32m   1319[0m     [38;5;66;03m# We need hue_order and hue_names because the former is used to control[39;00m
[1;32m   1320[0m     [38;5;66;03m# the order of drawing and the latter is used to control the order of[39;00m
[0;32m   (...)[0m
[1;32m   1325[0m     [38;5;66;03m# to the axes-level functions, while always handling legend creation.[39;00m
[1;32m   1326[0m     [38;5;66;03m# See GH2307[39;00m
[0;32m-> 1327[0m     hue_names [38;5;241m=[39m hue_order [38;5;241m=[39m categorical_order([43mdata[49m[43m[[49m[43mhue[49m[43m][49m, hue_order)
[1;32m   1328[0m     [38;5;28;01mif[39;00m dropna:
[1;32m   1329[0m         [38;5;66;03m# Filter NA from the list of unique hue names[39;00m
[1;32m   1330[0m         hue_names [38;5;241m=[39m [38;5;28mlist[39m([38;5;28mfilter[39m(pd[38;5;241m.[39mnotnull, hue_names))

File [0;32m~/.local/lib/python3.12/site-packages/pandas/core/frame.py:4102[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   4100[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mnlevels [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   4101[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getitem_multilevel(key)
[0;32m-> 4102[0m indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   4103[0m [38;5;28;01mif[39;00m is_integer(indexer):
[1;32m   4104[0m     indexer [38;5;241m=[39m [indexer]

File [0;32m~/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py:3812[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3807[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(casted_key, [38;5;28mslice[39m) [38;5;129;01mor[39;00m (
[1;32m   3808[0m         [38;5;28misinstance[39m(casted_key, abc[38;5;241m.[39mIterable)
[1;32m   3809[0m         [38;5;129;01mand[39;00m [38;5;28many[39m([38;5;28misinstance[39m(x, [38;5;28mslice[39m) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m casted_key)
[1;32m   3810[0m     ):
[1;32m   3811[0m         [38;5;28;01mraise[39;00m InvalidIndexError(key)
[0;32m-> 3812[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3813[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3814[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3815[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3816[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3817[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'species'

